#!/usr/bin/env python3
"""Apply the SkillOS public-safe copy policy.

This script is intentionally idempotent: it can run on every GitHub Actions build.
It updates public-facing copy to say "reference workflow" and "demo assumptions"
instead of implying audited customer results or guaranteed financial outcomes.
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

SAFE_NOTE_MD = """## Important public note

SkillOS is an open-source reference implementation. Current metrics are generated by one reproducible reference workflow in a controlled environment. They are not audited customer results, financial guarantees, investment advice, legal advice, medical advice, employment guidance, credit guidance, or promises of future outcomes.
"""

SAFE_PROOF_MD = """# SkillOS Reference Workflow Proof

SkillOS demonstrates, in one concrete reference workflow, how AI-agent work can become traces, traces can become tested skills, and tested skills can improve unit economics.

## What the proof shows

The current proof uses a controlled reference workflow: sales follow-up emails from call notes.

It demonstrates the mechanism:

```text
Work → Trace → Lesson → Candidate Skill → Test → Release → Better Unit Economics
```

## Important public note

Current metrics are generated by one reproducible reference workflow in a controlled environment. They are not audited customer results, financial guarantees, investment advice, legal advice, medical advice, employment guidance, credit guidance, or promises of future outcomes.

## Next step

Pilot 001 should test the same mechanism on real workflow data with human approval, privacy controls, and aggregated reporting only.
"""

REPLACEMENTS = [
    ("Agent SkillOS — Wealth-Accumulation Proof", "Agent SkillOS — Reference Workflow Proof"),
    ("The wealth-accumulation layer for self-improving AI agents.", "The work-compounding layer for self-improving AI agents."),
    ("The wealth-accumulation layer for self-improving AI agents", "The work-compounding layer for self-improving AI agents"),
    ("wealth-accumulation layer for self-improving AI agents", "work-compounding layer for self-improving AI agents"),
    ("wealth-accumulation layer", "work-compounding layer"),
    ("Wealth-accumulation proof", "Reference workflow proof"),
    ("Wealth Proof", "Reference Proof"),
    ("wealth proof", "reference proof"),
    ("Run SkillOS QA and build GitHub Pages site", "Apply safe copy, run SkillOS QA, and build GitHub Pages site"),
    ("One workflow improves across real skill releases.", "One reference workflow improves across tested skill releases."),
    ("SkillOS now proves one real workflow gets cheaper, faster, and better as agents do the work and repeated corrections become tested skill releases.", "SkillOS demonstrates, in one concrete reference workflow, how AI-agent work can become traces, traces can become tested skills, and tested skills can improve unit economics."),
    ("SkillOS proves one concrete workflow gets <strong>cheaper</strong>, <strong>faster</strong>, and <strong>better</strong> as agents do the work and repeated corrections become tested skill releases.", "SkillOS demonstrates, in one concrete reference workflow, how AI-agent work can become traces, traces can become tested skills, and tested skills can improve unit economics."),
    ("SkillOS proved one real workflow gets cheaper, faster, and better as agents do the work.", "SkillOS demonstrates one concrete reference workflow becoming cheaper, faster, and better through tested skill releases."),
    ("SkillOS proved one real workflow gets cheaper, faster, and better.", "SkillOS demonstrates one concrete reference workflow improving through tested skill releases."),
    ("One concrete workflow gets cheaper, faster, and better as agents do the work.", "One concrete reference workflow improves through tested skill releases."),
    ("One concrete workflow gets cheaper, faster, and better", "One concrete reference workflow improves through tested skill releases"),
    ("one real workflow", "one concrete reference workflow"),
    ("real workflow", "reference workflow"),
    ("real skill releases", "tested skill releases"),
    ("Work becomes traces. Traces become skills. Skills become margin.", "Work becomes traces. Traces become skills. Skills improve future work."),
    ("wealth-producing capability", "reusable capability"),
    ("wealth-producing", "work-improving"),
    ("Second, it proves one concrete wealth-accumulation workflow:", "Second, it demonstrates one concrete reference workflow:"),
    ("wealth-accumulation workflow", "reference workflow"),
    ("Annual savings", "Projected annual savings under demo assumptions"),
]

# Regex rules for context-sensitive phrases.
REGEX_REPLACEMENTS = [
    (re.compile(r"projected annual savings(?! under demo assumptions)", re.IGNORECASE), "projected annual savings under demo assumptions"),
    (re.compile(r"Projected annual savings(?! under demo assumptions)"), "Projected annual savings under demo assumptions"),
    (re.compile(r"annual savings vs human baseline", re.IGNORECASE), "projected annual savings under demo assumptions vs human baseline"),
    (re.compile(r"Projected at 10,000 jobs/year\.?", re.IGNORECASE), "Projected at 10,000 jobs/year under demo assumptions."),
]

TEXT_EXTENSIONS = {'.html', '.md', '.js', '.py', '.json', '.yml', '.yaml', '.txt', '.webmanifest'}
PUBLIC_PATH_HINTS = ('site', 'dist', 'docs', 'data', 'README', 'PROOF')


def is_text_target(path: Path) -> bool:
    if path.suffix not in TEXT_EXTENSIONS:
        return False
    parts = set(path.parts)
    if any(part.startswith('.') and part not in {'.github'} for part in parts):
        return False
    # Avoid patching this script's replacement table repeatedly in weird ways.
    if path.name in {'apply_safe_public_copy.py', 'verify_safe_public_copy.py'}:
        return False
    rel = str(path.relative_to(ROOT))
    return any(hint in rel for hint in PUBLIC_PATH_HINTS) or rel in {'index.html', 'README.md', 'PROOF_OF_WEALTH_ACCUMULATION.md'} or rel.startswith('skillos/') or rel.startswith('scripts/qa_check.py')


def patch_text(text: str) -> str:
    original = text
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)
    for pattern, new in REGEX_REPLACEMENTS:
        text = pattern.sub(new, text)
    return text


def ensure_readme_note(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text(encoding='utf-8')
    if 'SkillOS is an open-source reference implementation' in text:
        return False
    lines = text.splitlines()
    insert_at = 0
    if lines and lines[0].startswith('#'):
        insert_at = 1
        # Preserve one blank after title if present.
        if len(lines) > 1 and lines[1].strip() == '':
            insert_at = 2
    new_lines = lines[:insert_at] + [SAFE_NOTE_MD.rstrip(), ''] + lines[insert_at:]
    path.write_text('\n'.join(new_lines).rstrip() + '\n', encoding='utf-8')
    return True


def write_safe_proof(path: Path) -> bool:
    if not path.exists():
        return False
    old = path.read_text(encoding='utf-8')
    if old.strip() == SAFE_PROOF_MD.strip():
        return False
    path.write_text(SAFE_PROOF_MD, encoding='utf-8')
    return True


def apply(write: bool = True) -> list[str]:
    changed: list[str] = []
    for path in ROOT.rglob('*'):
        if path.is_file() and is_text_target(path):
            try:
                text = path.read_text(encoding='utf-8')
            except UnicodeDecodeError:
                continue
            patched = patch_text(text)
            if patched != text:
                if write:
                    path.write_text(patched, encoding='utf-8')
                changed.append(str(path.relative_to(ROOT)))

    # Overwrite legacy proof markdown with safe public-safe copy.
    proof_path = ROOT / 'PROOF_OF_WEALTH_ACCUMULATION.md'
    if write_safe_proof(proof_path):
        changed.append(str(proof_path.relative_to(ROOT)))

    # Ensure README disclaimer.
    readme_path = ROOT / 'README.md'
    if ensure_readme_note(readme_path):
        changed.append(str(readme_path.relative_to(ROOT)))

    # If dist exists, patch generated dist too.
    for path in (ROOT / 'dist').rglob('*') if (ROOT / 'dist').exists() else []:
        if path.is_file() and path.suffix in TEXT_EXTENSIONS:
            try:
                text = path.read_text(encoding='utf-8')
            except UnicodeDecodeError:
                continue
            patched = patch_text(text)
            if patched != text:
                if write:
                    path.write_text(patched, encoding='utf-8')
                changed.append(str(path.relative_to(ROOT)))
    return sorted(set(changed))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true', help='Check only; exit 1 if changes would be made.')
    parser.add_argument('--write', action='store_true', help='Apply changes. Default behavior is write.')
    args = parser.parse_args()
    write = not args.check
    changed = apply(write=write)
    if changed:
        action = 'Changed' if write else 'Would change'
        print(f'{action} {len(changed)} file(s):')
        for item in changed:
            print(f' - {item}')
        if args.check:
            raise SystemExit(1)
    else:
        print('Safe public copy already applied; no changes needed.')

if __name__ == '__main__':
    main()
