from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = [
    ".github/workflows/pages.yml",
    ".github/workflows/tests.yml",
    "README.md",
    "README_FIRST_GITHUB_WEB_USERS.md",
    "PROOF_OF_WEALTH_ACCUMULATION.md",
    "skillos/wealth_proof.py",
    "tests/test_wealth_proof.py",
    "site/index.html",
    "site/app.js",
    "site/styles.css",
    "scripts/apply_safe_public_copy.py",
    "scripts/verify_safe_public_copy.py",
]


def fail(message: str) -> None:
    print(f"ERROR: {message}")
    raise SystemExit(1)


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def write_report(path: Path, proof: dict) -> None:
    unit = proof["unit_economics"]
    report = f"""# SkillOS Reference Workflow Proof

**Claim:** {proof['claim']}

**Workflow:** {proof['workflow']}

## Result

- Skill version: v{proof['initial_agent']['version']} → v{proof['final_agent']['version']}
- Quality score: {unit['quality_score_initial_to_final']}
- Accepted rate: {unit['accepted_rate_initial_to_final']}
- Minutes per job: {unit['minutes_per_job_initial_to_final']}
- Cost per job: {unit['cost_per_job_initial_to_final_usd']}
- Cost reduction vs initial agent: {unit['cost_reduction_vs_initial_agent_percent']}%
- Speed gain vs initial agent: {unit['speed_gain_vs_initial_agent_percent']}%
- Projected annual savings under demo assumptions vs human baseline: ${unit['projected_annual_savings_vs_human_usd']:,.0f}

## Important public note

Current metrics are generated by one reproducible reference workflow in a controlled environment. They are not audited customer results, financial guarantees, investment advice, legal advice, medical advice, employment guidance, credit guidance, or promises of future outcomes.

## Gate Checks

"""
    for name, value in proof["monotonic_checks"].items():
        report += f"- {'✅' if value else '❌'} {name.replace('_', ' ')}\n"
    report += "\n## Interpretation\n\nThis is a deterministic reference proof. It demonstrates the mechanism: completed jobs create traces, traces create lessons, lessons become candidate skill updates, and only skill updates that improve quality, speed, and cost are released. Pilot 001 should swap in real jobs, human feedback, and model/tool integrations while keeping these gates.\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report, encoding="utf-8")


def build_site(proof: dict) -> None:
    dist = ROOT / "dist"
    if dist.exists():
        shutil.rmtree(dist)
    shutil.copytree(ROOT / "site", dist)
    (dist / "data").mkdir(exist_ok=True)
    write_json(dist / "data" / "wealth_proof.json", proof)
    shutil.copy2(ROOT / "docs" / "wealth_accumulation_proof.md", dist / "wealth_accumulation_proof.md")
    (dist / ".nojekyll").write_text("", encoding="utf-8")
    required_dist = ["index.html", "app.js", "styles.css", "data/wealth_proof.json", "wealth_accumulation_proof.md"]
    for rel in required_dist:
        if not (dist / rel).exists():
            fail(f"dist missing {rel}")


def run_safe_copy() -> None:
    import importlib.util
    script = ROOT / "scripts" / "apply_safe_public_copy.py"
    spec = importlib.util.spec_from_file_location("apply_safe_public_copy", script)
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    spec.loader.exec_module(mod)
    changed = mod.apply(write=True)
    if changed:
        print("Safe public copy applied inside QA:")
        for item in changed:
            print(f" - {item}")


def main() -> None:
    for rel in REQUIRED:
        if not (ROOT / rel).exists():
            fail(f"required file missing: {rel}")
    print("Repository file verification passed")
    run_safe_copy()
    sys.path.insert(0, str(ROOT))
    from skillos.wealth_proof import run_wealth_proof
    proof = run_wealth_proof()
    if not proof["proof_passed"]:
        fail("reference workflow proof failed")
    write_json(ROOT / "data" / "wealth_proof.json", proof)
    write_report(ROOT / "docs" / "wealth_accumulation_proof.md", proof)
    print("Reference workflow proof generated")
    result = subprocess.run([sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"], cwd=ROOT, text=True, capture_output=True)
    print(result.stdout, end="")
    print(result.stderr, end="")
    if result.returncode != 0:
        fail("unit tests failed")
    build_site(proof)
    run_safe_copy()
    print("GitHub Pages build generated")
    html = (ROOT / "dist" / "index.html").read_text(encoding="utf-8")
    for needle in ["work-compounding", "Sales follow-up", "data/wealth_proof.json", "reference workflow"]:
        if needle not in html:
            fail(f"site verification failed: missing {needle}")
    # Final safe-copy check.
    result = subprocess.run([sys.executable, "scripts/verify_safe_public_copy.py", "--strict"], cwd=ROOT, text=True, capture_output=True)
    print(result.stdout, end="")
    print(result.stderr, end="")
    if result.returncode != 0:
        fail("safe public copy verification failed")
    print("GitHub Pages verification passed")
    print("Repository QA passed")


if __name__ == "__main__":
    main()
